server:
  port: ${PORT:8761}

spring:
  application:
    name: discovery-serivce

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    renewalPercentThreshold: 0.49

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF